# Welcome to numpy tutorial


1. Numpy provides efficient storage.
2. It also provides better ways of handling data for processing
3.Numpy uses relatively less memory to store data

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,32,7])

In [3]:
print(myarr)

[ 3  6 32  7]


In [4]:
 myarr

array([ 3,  6, 32,  7])

Memory Management

In [5]:
myarr=np.array([3,6,32,7],np.int64)  #use 64 bytes to store array

In [6]:
myarr   

array([ 3,  6, 32,  7], dtype=int64)

In [7]:
myarr[0]

3

* myarr.shape -> .shape as a attribute not function

In [8]:
myarr.shape  #4 column

(4,)

In [9]:
myarr=np.array([[3,6,32,7]],np.int64)  #two dimensional array
                                       

In [10]:
myarr[0,2]

32

In [11]:
myarr.shape   #1 rows, 4 columns

(1, 4)

In [12]:
myarr.dtype   #64 bites(16 bytes)

dtype('int64')

dtype means data type

In [13]:
myarr[0,1]=45

In [14]:
myarr    #we can change the value in array by its index

array([[ 3, 45, 32,  7]], dtype=int64)

# Array creation: Conversion from other Python structures

*** Made array using list and tuples***

In [15]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
np.array({21,12,14})   #object is not efficient

array({12, 21, 14}, dtype=object)

# Intrinsic numpy array creation objects

***e.g.,arange,ones,zeros,etc.***

*ZEROS*


In [21]:
zeros=np.zeros((2,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zeros.shape

(2, 5)

In [24]:
zeros.dtype

dtype('float64')

*ARANGE*

In [25]:
rng=np.arange(15)  #0-14numbers print in form of list in array

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*LINSPACE*

In [27]:
lspace=np.linspace(1,50,10)   #its means that print 10 number between 1 and 50
                             # which is ineraly equally spaced(difference) between two consecutive number 

In [28]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
lspace=np.linspace(1,4,4)  #(start,end,total number)

In [30]:
lspace  #no. between 1 and 4 (total 4 number)

array([1., 2., 3., 4.])

***Uses of EMPTY***

In [31]:
emp=np.empty((5,6))

In [32]:
emp     #print 5 rows,6 column array with random element
        #it is uses to add some value in empty array

array([[1.02480255e-311, 9.78249979e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [6.64457828e-066, 9.76119609e+165, 1.25693486e-075,
        6.59761642e-042, 4.90861281e-062, 3.59751658e+252],
       [8.93185432e+271, 4.76484771e+180, 1.47763641e+248,
        1.16096346e-028, 7.69165785e+218, 1.35617292e+248],
       [2.13875455e+184, 5.45180571e-067, 1.42555062e+160,
        8.03252962e-042, 5.43384597e-143, 1.16097020e-028],
       [1.68890874e-052, 1.48375018e-071, 2.31655669e-052,
        1.11763122e+261, 1.16318408e-028, 6.79764374e-310]])

***emp_like***

In [33]:
emp_like=np.empty_like(lspace)

In [34]:
emp_like

array([1., 2., 3., 4.])

***identity***

In [35]:
ide=np.identity(45)  #print 45x45 matrix

In [36]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

***RESHAPE***


In [38]:
arr=np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.reshape(3,33)  #reshape it and print arr in 3x33 matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr   # till  arr is not change

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr=arr.reshape(3,33)

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

 ***ravel-to make systematic manner(sidha)***
    

In [44]:
arr=arr.ravel()

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.shape   #99 elements

(99,)

# Numpy Axis

* 1D-> [1,2,3,4,5]  ->1axis [Axis0]

* 2D->[[1,2,3],[12,13,14],[5,6,7]] ->2axis [Axis0,Axis1]

*in 2D
 * axis0 along column 
 *axis1 is along row [1,2,3]

In [47]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [48]:
ar=np.array(x)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
ar.sum(axis=0)   #1+4+7=12
                 #2+5+1=8
                 #3+6+0=9

array([12,  8,  9])

In [51]:
ar.sum(axis=1)   #1+2+3=6   4+5+6=15   7+1+0=8

array([ 6, 15,  8])

***Transpose***

In [52]:
ar.T   

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [53]:
ar.flat

In [54]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [55]:
ar.ndim   #for dimension

2

In [56]:
ar.size

9

In [57]:
ar.nbytes  #total bytes consumed

36

In [58]:
one=np.array([1,3,4,534,2])

In [59]:
one.argmax() #it is function
              #

3

In [60]:
one.argmin()  #it gives index of minimum value

0

In [61]:
one.argsort()   #it give indexes of number in increasing order

array([0, 4, 1, 2, 3], dtype=int64)

***use above in 2D*** 

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar.argmin()  #it made staright array then print index of min. element

8

In [64]:
ar.argmax()

6

In [65]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [66]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [67]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [68]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [69]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [70]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
ar+ar2   #it adds values at sames indexes in both matrix

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

*Let's check it is possible in lists or not?

In [74]:
[12,13]+[1,2]

[12, 13, 1, 2]

absolutely not

In [75]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
np.sqrt(ar)  #for square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [78]:
ar.sum()  #sum of all element

29

In [79]:
np.where(ar>5)  #find element by its index

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [80]:
type(np.where(ar>5))

tuple

In [81]:
np.count_nonzero(ar)

8

In [82]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

*** Now,let's see importance of numpy***

In [83]:
import sys

In [84]:
py_ar=[0,4,55,2]

In [85]:
np_ar=np.array(py_ar)

In [86]:
sys.getsizeof(1) * len(py_ar)

112

In [87]:
np_ar.itemsize * np_ar.size

16

*see the difference between sizes of normally python program vs numpy 

**For more attributes search numpy.ndarray**

 

docs.scipy.org

#     Thanks!